cc_test(
  name = "emulator_payload_com_test",
  srcs = ["emulator_payload_com_test.cc"],
  deps = ["//emulator_liason/public:emulator_liason",
  "//emulator/public:emulator", 
          "@com_google_googletest//:gtest_main"],
)

