load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "gpo",
    hdrs = [
        "gpo.h",
    ],
    visibility = ["//libs/cpp/hal/gpio/public:__pkg__"],
)

cc_library(
    name = "gpi",
    hdrs = [
        "gpi.h",
    ],
    visibility = ["//libs/cpp/hal/gpio/public:__pkg__"],
)
