
cc_library(
  name = "emulator",
  srcs = ["//emulator/src:emulator.cc"],
  hdrs = ["emulator.h"],
  visibility = ["//visibility:public"], 
  deps = ["//abstraction_layer:serial_communication_interface", 
          "//abstraction_layer:gpio_interface"],
)
