
cc_library(
  name = "emulator_liason",
  srcs = ["//emulator_liason/src:emulator_liason.cc"],
  hdrs = ["emulator_liason.h"],
  visibility = ["//visibility:public"], 
  deps = ["//abstraction_layer:serial_communication_interface", 
          "//abstraction_layer:gpio_interface",
          "//abstraction_layer:time_interface"],
)
