
cc_test(
  name = "emulator_liason_test",
  srcs = ["emulator_liason_test.cc"],
  deps = ["//emulator_liason/public:emulator_liason",
          "//external_libraries:arduino_json", 
          "@com_google_googletest//:gtest_main",
          "//emulator_definitions:emulator_definitions"],
)

